#!/usr/bin/env zsh
#
# Ivan Angelov ivangotoy@gmail.com
# https://digtvbg.com/
#
# Tooling used: zsh, curl, jq, and column
#
# This script does these things:
# 
# Shows a list of country to number mappings for NORDVPN
#
# Asks the user to select a number
#
# Pulls valuable details for the country represented by the selected number.
#
# Any anonymous aliexpress trader would not care if the number was valid so do we :)

export LC_ALL=C
export LANG=C

# Show countries:
printf "AVAILABLE COUNTRIES + THEIR NUMERIC CODES:\n"
printf "#########################################:\n"
curl  --tlsv1.3 --silent --compressed -4 --dns-ipv4-addr 192.168.1.1 --http2 --parallel --parallel-immediate --sasl-ir "https://api.nordvpn.com/v1/servers/countries" | jq --raw-output '.[] | [.id, .name] | @tsv' | column -c 70

printf "PLEASE ENTER YOUR DESIRED COUNTRY NUMERIC CODE AND PRESS ENTER:\n"
read;
# $REPLY IS THE NUMBER

printf "HERE ARE THE WIREGUARD SERVERS FROM COUNTRY ID "${REPLY}" SORTED BY LOAD:\n"

LIST="$(curl  --tlsv1.3 --silent --compressed -4 --dns-ipv4-addr 192.168.1.1 --http2 --parallel --parallel-immediate --sasl-ir "https://api.nordvpn.com/v1/servers?filters\[servers_technologies\]\[identifier\]=wireguard_udp&filters\[country_id\]="$REPLY"&limit=20" | jq --raw-output --slurp ' .[] | sort_by(.load) | limit(20;.[]) | [.hostname, .station, (.technologies|.[].metadata|.[].value), .load] | "\(.[0])  \(.[1])  \(.[2])  \(.[3])"')"

printf "HOST IP PUBKEY LOAD\n "$LIST"" | column -t
printf "PORT NUMBER IS ALWAYS: 51820\n"
